<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>Kobayashi Ryu</Authors>
    <Description>Scrape from Riot Api and deserialize. Just for LoL.</Description>
    <PackageTags>LoL, Riot, LeagueOfLegends</PackageTags>
    <AssemblyVersion>2.5.2.3</AssemblyVersion>
    <Version>$(VersionPrefix)2.5.2.3</Version>
    <Title>beta</Title>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="RiotApiWrapper.Test" />
  </ItemGroup>


</Project>
